title: Javad Shiekh
description: A blog about me an my projects
username: Javad Sheikh
user_description: >-
  I'm a Artificial Intelligence Master of Science student at Amirkabir university of Tehran. 
user_title: Artificial Intelligence developer
email: Javad@n@yahoo.com
github_username: Javad-shiekh
google-analytics:
  id: ''
exclude:
  - package.json
  - src
  - node_modules
baseurl: ''
url: ''
