title: Javad Shiekh
description: A blog about me an my projects
username: Javad Sheikh
user_description: >-
  I have found my passion for coding and Artificial Intelligence during my undergraduate study in biomedical engineering. So I got into a Master's of Science in Artificial Intelligence at Amirkabir University of Technology(Tehran Polytechnic). I have studied many AI and ML approaches since then and have coded many projects using them. In this blog, I will demonstrate some of them. 
  I have code in many languages. The first coding language I learned is C++, and I have used it in various projects. I have mastered python for data science projects. I also have been working as an android developer using Java. In my recent projects, I have combined my passion for AI in android software development. I have made several AI-powered android apps.
user_title: Artificial Intelligence developer
email: Javad2n@yahoo.com
github_username: Javad-shiekh
google-analytics:
  id: ''
exclude:
  - package.json
  - src
  - node_modules
baseurl: ''
url: ''
